### ISSUE TITLE
Need more documentation to use gnbsim

### ISSUE THREAD

**Issue by lpatil81** [omec-project/gnbsim#129]
First, It is great project. But, I do not see enough documentation. I am eager to add doc contributions. Can admin enable wiki for this project.

**Comment by gab-arrobo** [comment]
@lpatil81, here is an easy way to start using `gnbsim` along with the [Aether SD-Core network](https://docs.aetherproject.org/master/onramp/start.html). The usage documentation is [here](https://docs.sd-core.opennetworking.org/master/developer/gnbsim.html) and its deployment information is [here](https://docs.sd-core.opennetworking.org/master/deployment/deploymentgnbsim.html).
We are in the process of moving the documentation from `Gerrit` to `GitHub`, so it is easy to contribute improvements to the documentation.

**Comment by gab-arrobo** [comment]
@lpatil81 feel free to open PRs to improve the documentation in here: https://github.com/omec-project/sdcore-docs

**Comment by thakurajayL** [comment]
@gab-arrobo  is new repo setup and working?

**Comment by gab-arrobo** [comment]
> @lpatil81, here is an easy way to start using `gnbsim` along with the [Aether SD-Core network](https://docs.aetherproject.org/master/onramp/start.html). The usage documentation is [here](https://docs.sd-core.opennetworking.org/master/developer/gnbsim.html) and its deployment information is [here](https://docs.sd-core.opennetworking.org/master/deployment/deploymentgnbsim.html). We are in the process of moving the documentation from `Gerrit` to `GitHub`, so it is easy to contribute improvements to the documentation.

@lpatil81 is this still an issue? or can I close it?
