### ISSUE TITLE
How to set OPc and Key ?

### ISSUE THREAD

**Issue by orion-belt** [omec-project/gnbsim#57]
In [config file](https://github.com/omec-project/gnbsim/blob/main/config/gnbsim.yaml) there is no field for OPc and Key. 
Will you please tell us how it can be configured to test with different core networks ?

**Comment by thakurajayL** [comment]
HI. You found it right. Current we are importing CommonConsumerTestData and using the keys in those packages. Ideally we wish to have opc & key in the profile and use it. I had opened internal task for it but did not complete it. Do you have bandwidth to do it or you are looking for solution from us?

**Comment by orion-belt** [comment]
@thakurajayL 
Thanks for the response. I am trying to test it with OAI-CN. But, I am not sure if I can address it in near time. 
I am looking for solution from your team if it is possible.

Thanks

**Comment by thakurajayL** [comment]
I have fix for this. Should raise pull request tomorrow.

**Comment by thakurajayL** [comment]
I have committed changes and new build is also generated. Helm charts are updated with new image.

New image tag - omecproject/5gc-gnbsim:main-238bdee
