### ISSUE TITLE
Invalid S-NSSAI

### ISSUE THREAD

**Issue by orion-belt** [omec-project/gnbsim#58]
Standardized S-NSSAI (SST= 1 to 127) has only SST and no SD value (TS 23.501, R16.0.0., 5.15.2.1).
Hence S-NSSAI with SST, SD = 1, 010203 in sample [config file](https://github.com/omec-project/gnbsim/blob/main/config/gnbsim.yaml) is invalid actually.

**Comment by thakurajayL** [comment]
Welcome to community and thanks for reporting this.  Would you be able to raise pull request for this ?

**Comment by orion-belt** [comment]
Actually it need to be handled internally in code.
```bash
no SD value   => 0xFFFFFF (TS 23.003, R16.0.0., 28.4.2)
```

I will try to create PR for this.
