### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by orion-belt** [omec-project/gnbsim#63]
Hello <br/>
 I have seen that following values are hardcoded in the message, and it will be great if we can configure them in the config file.

1. TAC in the UplinkNASTransport(RegistrationRequest)
![Screenshot from 2022-08-02 15-18-41](https://user-images.githubusercontent.com/44278749/182395255-f754440e-c16f-439a-8c69-0a1975a3389b.png)
<br/>

2. SNSSAI, DNN in PDUSessionEstablishment request
![Screenshot from 2022-08-02 15-27-52](https://user-images.githubusercontent.com/44278749/182395611-bd98264b-70d7-4075-b6b7-3c3409a77b91.png)
<br/>

3. Procedure transaction id, it should be > =1 in PDUSessionEstablishment request
![Screenshot from 2022-08-02 16-12-03](https://user-images.githubusercontent.com/44278749/182395960-a496bf81-b2e5-42f5-a062-92008e736d8f.png)

**Comment by thakurajayL** [comment]
Thanks. Do you have bandwidth to work on this issue ? We will be happy to receive contributions from you !

**Comment by orion-belt** [comment]
Hi @thakurajayL 
To created PR to fix invalid PTI value
https://github.com/omec-project/nas/pull/9

**Comment by thakurajayL** [comment]
Thanks.

**Comment by gajjarvini** [comment]
Hello @orion-belt , thank you very much for reporting this issue, I can see that you have already raised a PR for NSSAI and DNN.
I have taken up the task for removing hardcoding for UE Location, and have raise a PR for the same
