### ISSUE TITLE
gNBSim should support executing subscribers call flow in parallel

### ISSUE THREAD

**Issue by thakurajayL** [omec-project/gnbsim#66]
AS of today, gNBSim generates call flow events for all the subscribers within profile in sequential manner.
We wish to support option in the profile to support multiple subscriber call model execution in parallel.

**Comment by gab-arrobo** [comment]
@thakurajayL, this feature is already implemented, no?

**Comment by thakurajayL** [comment]
Yes. This is already supported.

**Comment by thakurajayL** [comment]
executeInParallel: true at the top level config  means all the profiles run in parallel
execureInParallel:true within profile means run all the subscribers in parallel within the profile.
