### ISSUE TITLE
Servings network name is hardcoded

### ISSUE THREAD

**Issue by orion-belt** [omec-project/gnbsim#68]
Servings network name is hard-coded with MCC, MNC value.
It will be good if MCC, MNC from config is used.

https://github.com/omec-project/gnbsim/blob/main/realue/handler.go#L27

**Comment by thakurajayL** [comment]
Thank You @orion-belt . Do you have bandwidth for this issue ?

**Comment by orion-belt** [comment]
Hi @thakurajayL 
Sorry. I am quite occupied, but i will try to check it out.

**Comment by thakurajayL** [comment]
Sure. @orion-belt  & @gajjarvini  if you have proposal about how this can be fixed and where we can have configuration then I can see how to add this support. Thank You

**Comment by orion-belt** [comment]
We should create SN_NAME here
https://github.com/omec-project/gnbsim/blob/main/realue/handler.go#L57 by extracting MNC and MCC info from object `ue.Plmn.mcc` & `ue.Plmn.mnc`. I tried this but looks like it is still hardcoded in some upstream. Then we can keep realm (`3gppnetwork.org`) as it is.
